// src/app/data.ts
import type { Category, Ingredient } from "./types";

// Handy for rendering checkbox lists etc.
export const CATEGORIES: { key: Category; label: string }[] = [
  { key: "Protein",       label: "Protein" },
  { key: "Carbohydrate",  label: "Carbohydrate" },
  { key: "Vegetable",     label: "Vegetable" },
  { key: "Fruit",         label: "Fruit" },
  { key: "Fat",           label: "Fat" },
];

// All nutrition values are per 100 g (approx.)
// cookingTime is a rough prep+cook estimate in minutes.
export const INGREDIENTS: Ingredient[] = [
  // --- Proteins ---
  {
    id: "chicken-breast",
    name: "Chicken breast",
    category: "Protein",
    cookingTime: 20,
    calories: 165,
    protein: 31,
    carbohydrates: 0,
    fat: 3.6,
    imageUrl: "/images/ingredients/chicken-breast.jpg",
  },
  {
    id: "tofu-firm",
    name: "Tofu (firm)",
    category: "Protein",
    cookingTime: 10,
    calories: 76,
    protein: 8,
    carbohydrates: 1.9,
    fat: 4.8,
    imageUrl: "/images/ingredients/tofu.jpg",
  },
  {
    id: "eggs",
    name: "Eggs",
    category: "Protein",
    cookingTime: 8,
    calories: 143,
    protein: 13,
    carbohydrates: 1.1,
    fat: 10.6,
    imageUrl: "/images/ingredients/eggs.jpg",
  },
  {
    id: "salmon",
    name: "Salmon",
    category: "Protein",
    cookingTime: 12,
    calories: 208,
    protein: 20,
    carbohydrates: 0,
    fat: 13,
    imageUrl: "/images/ingredients/salmon.jpg",
  },
  {
    id: "greek-yoghurt",
    name: "Greek yoghurt (low-fat)",
    category: "Protein",
    cookingTime: 0,
    calories: 59,
    protein: 10,
    carbohydrates: 3.6,
    fat: 0.4,
    imageUrl: "/images/ingredients/greek-yoghurt.jpg",
  },

  // --- Carbohydrates ---
  {
    id: "brown-rice-cooked",
    name: "Brown rice (cooked)",
    category: "Carbohydrate",
    cookingTime: 12, // 2 if microwave pouch
    calories: 123,
    protein: 2.7,
    carbohydrates: 25.6,
    fat: 1.0,
    imageUrl: "/images/ingredients/brown-rice.jpg",
  },
  {
    id: "quinoa-cooked",
    name: "Quinoa (cooked)",
    category: "Carbohydrate",
    cookingTime: 15,
    calories: 120,
    protein: 4.4,
    carbohydrates: 21.3,
    fat: 1.9,
    imageUrl: "/images/ingredients/quinoa.jpg",
  },
  {
    id: "sweet-potato",
    name: "Sweet potato (steamed/baked)",
    category: "Carbohydrate",
    cookingTime: 7, // microwave/steam small cubes
    calories: 86,
    protein: 1.6,
    carbohydrates: 20.1,
    fat: 0.1,
    imageUrl: "/images/ingredients/sweet-potato.jpg",
  },
  {
    id: "wholewheat-pasta-cooked",
    name: "Wholewheat pasta (cooked)",
    category: "Carbohydrate",
    cookingTime: 10,
    calories: 124,
    protein: 5.3,
    carbohydrates: 26.9,
    fat: 0.9,
    imageUrl: "/images/ingredients/wholewheat-pasta.jpg",
  },
  {
    id: "rolled-oats",
    name: "Rolled oats (dry)",
    category: "Carbohydrate",
    cookingTime: 5, // stovetop/quick soak
    calories: 389,
    protein: 16.9,
    carbohydrates: 66.3,
    fat: 6.9,
    imageUrl: "/images/ingredients/oats.jpg",
  },

  // --- Vegetables ---
  {
    id: "broccoli-steamed",
    name: "Broccoli (steamed)",
    category: "Vegetable",
    cookingTime: 5,
    calories: 35,
    protein: 2.4,
    carbohydrates: 7.2,
    fat: 0.4,
    imageUrl: "/images/ingredients/broccoli.jpg",
  },
  {
    id: "spinach",
    name: "Baby spinach",
    category: "Vegetable",
    cookingTime: 1,
    calories: 23,
    protein: 2.9,
    carbohydrates: 3.6,
    fat: 0.4,
    imageUrl: "/images/ingredients/spinach.jpg",
  },
  {
    id: "capsicum",
    name: "Capsicum (red pepper)",
    category: "Vegetable",
    cookingTime: 3,
    calories: 31,
    protein: 1.0,
    carbohydrates: 6.0,
    fat: 0.3,
    imageUrl: "/images/ingredients/capsicum.jpg",
  },
  {
    id: "tomato",
    name: "Tomato",
    category: "Vegetable",
    cookingTime: 0,
    calories: 18,
    protein: 0.9,
    carbohydrates: 3.9,
    fat: 0.2,
    imageUrl: "/images/ingredients/tomato.jpg",
  },
  {
    id: "carrot",
    name: "Carrot",
    category: "Vegetable",
    cookingTime: 5,
    calories: 41,
    protein: 0.9,
    carbohydrates: 9.6,
    fat: 0.2,
    imageUrl: "/images/ingredients/carrot.jpg",
  },

  // --- Fruits ---
  {
    id: "banana",
    name: "Banana",
    category: "Fruit",
    cookingTime: 0,
    calories: 89,
    protein: 1.1,
    carbohydrates: 22.8,
    fat: 0.3,
    imageUrl: "/images/ingredients/banana.jpg",
  },
  {
    id: "blueberries",
    name: "Blueberries",
    category: "Fruit",
    cookingTime: 0,
    calories: 57,
    protein: 0.7,
    carbohydrates: 14.5,
    fat: 0.3,
    imageUrl: "/images/ingredients/blueberries.jpg",
  },
  {
    id: "apple",
    name: "Apple",
    category: "Fruit",
    cookingTime: 0,
    calories: 52,
    protein: 0.3,
    carbohydrates: 14.0,
    fat: 0.2,
    imageUrl: "/images/ingredients/apple.jpg",
  },
  {
    id: "orange",
    name: "Orange",
    category: "Fruit",
    cookingTime: 0,
    calories: 47,
    protein: 0.9,
    carbohydrates: 12.0,
    fat: 0.1,
    imageUrl: "/images/ingredients/orange.jpg",
  },

  // --- Fats ---
  {
    id: "olive-oil",
    name: "Olive oil",
    category: "Fat",
    cookingTime: 0,
    calories: 884,
    protein: 0,
    carbohydrates: 0,
    fat: 100,
    imageUrl: "/images/ingredients/olive-oil.jpg",
  },
  {
    id: "avocado",
    name: "Avocado",
    category: "Fat",
    cookingTime: 1,
    calories: 160,
    protein: 2.0,
    carbohydrates: 9.0,
    fat: 15.0,
    imageUrl: "/images/ingredients/avocado.jpg",
  },
  {
    id: "peanut-butter",
    name: "Peanut butter",
    category: "Fat",
    cookingTime: 0,
    calories: 588,
    protein: 25,
    carbohydrates: 20,
    fat: 50,
    imageUrl: "/images/ingredients/peanut-butter.jpg",
  },
  {
    id: "almonds",
    name: "Almonds",
    category: "Fat",
    cookingTime: 0,
    calories: 579,
    protein: 21,
    carbohydrates: 22,
    fat: 50,
    imageUrl: "/images/ingredients/almonds.jpg",
  },
];
